messages:
    player_death: "{GRAY}{BOLD}[{GREEN}{BOLD}!{GRAY}{BOLD}] {YELLOW}{PLAYER_NAME} {GRAY}died {GRAY}{BOLD}[{GRAY}{DEATH_CAUSE}{GRAY}{BOLD}][{RED}{DAMAGE}{GRAY}{BOLD}] [{YELLOW}W{GRAY}:{WORLD}{GRAY}{BOLD}][{YELLOW}X{GRAY}:{POSX}{GRAY}{BOLD}][{YELLOW}Y{GRAY}:{POSY}{GRAY}{BOLD}][{YELLOW}Z{GRAY}:{POSZ}{GRAY}{BOLD}]"
